import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

function CompletePage() {

    return (
        <div className={styles.containerQuiz}>
            <Head>
            <title>Let's Go Biotech - Take Quiz</title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <a className={styles.missionLaunch} href="/read-papers"><b>BACK</b></a> 
                <h1 className={styles.titleQuiz}>
                    🧬 Let's Go Biotech - Good Stuff! 🚀
                </h1>   
                <div className={styles.quizFun}>
                    <h2> <i>Damn.</i> You is smart. The AI said you got all the answers correct!</h2>
                    <a className={styles.pinkSquare} href='/'><b>Wanna play again?</b></a> 
                </div>  
                </div>
            </div>
      );
}

export default CompletePage;