import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import SelectPaperButton from '../components/SelectPaperButton';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Let's Go Biotech - Home Base</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        🧬 Welcome to Let's Go Biotech 🚀
        </h1> 
       <br />
        <p className={styles.description}>
          <i>Keep updated with the Latest Research in Biotechnology</i>{' '}
        </p>
        <div className={styles.grid}>
          <a>
            <h2> (1) &rarr; Select from a Curated Set of Papers</h2>
          </a>
<br />
          <a>
            <h2> (2) &rarr; Read through whichever papers you find interesting and take a quiz on them!</h2>
          </a>
<br />
          <a>
            <h2>(3) &rarr; See your Score and Try to Improve it</h2>
          </a>
<br />
          <a href="/paper-curation" className={styles.greenSquare}>
            <h2>Let's Get Started</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
