import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

function TakeQuiz() {

    return (
        <div className={styles.containerQuiz}>
            <Head>
            <title>Let's Go Biotech - Take Quiz</title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <a className={styles.missionLaunch} href="/read-papers"><b>BACK</b></a> 

                <h1 className={styles.titleQuiz}>
                    🧬 Let's Go Biotech - Take Quiz 🚀
                </h1>   

                <br />

                <div className={styles.quizFun}>
                    (1) What is CRISPR? <br />
                    <select>
                        <option value="A">a tool to cut trees</option>
                        <option value="B">a tool for biological research</option>
                        <option value="C">a tool to get a rad tan</option>
                    </select> <br /> <br />
                    (2) Which of the following is NOT a field mentioned in the abstract that is going to be changed by 
                        CRISPR technology? <br />
                    <select>
                        <option value="A">medical research</option>
                        <option value="B">agriculture</option>
                        <option value="C">legal</option>
                    </select> <br /> <br />
                    (3) I'm curious, if you had to cure one disease which one would you choose? <br />
                    <input></input> <br /> <br />
                    <a className={styles.greenSquare} href='complete-page'><b>Finish Quiz</b></a>   
                </div>
            </div>

        </div>
      );
}

export default TakeQuiz;